[workspace]
members = [
    "bin/artemis",
    "bin/cli",
    "crates/artemis-core",
    "crates/generator",
    "crates/strategies/*",
    "crates/clients/*", 
    "examples/*",
]

default-members = ["bin/artemis"]

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

